POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpZGltc2tpIiwiaWQiOiI2MGVmZWZhNjVkODAzOTE3YjRkZmUzZDIiLCJpYXQiOjE2MjY0MzAzMzMsImV4cCI6MTYyNjQzMzkzM30.43XLXQWPHmKj2tyTgx9dq7-c6nKnMy_4t_LPeNv9n_I

{
    "title":"Token authorization",
    "author": "New Folder Structure",
    "url": "http://whatever.com",
    "likes": 20
}