POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpZGltc2tpIiwiaWQiOiI2MGVmZWZhNjVkODAzOTE3YjRkZmUzZDIiLCJpYXQiOjE2MjY0NTc4MDIsImV4cCI6MTYyNjQ2MTQwMn0.4s4JiDZuBgXM14Pv3L6mIFuMeivCgMZgG0GMiv3v4oc

{
    "title":"4.22",
    "author": "After started with tests",
    "url": "http://whatever.com",
    "likes": 20
}